//
// Generated by CocoaPods-Keys
// on 11/03/2017
// For more information see https://github.com/orta/cocoapods-keys
//

#import <Foundation/NSString.h>

NS_ASSUME_NONNULL_BEGIN

@interface WarsaroundKeys : NSObject

@property (readonly) NSString *googlePlacesToken;

@end

NS_ASSUME_NONNULL_END
